const examConfig = {
  "cbi": {
    "pages": [
      "assets/uam_booklets/cbi/page_1.png",
      "assets/uam_booklets/cbi/page_2.png",
      "assets/uam_booklets/cbi/page_3.png",
      "assets/uam_booklets/cbi/page_4.png",
      "assets/uam_booklets/cbi/page_5.png",
      "assets/uam_booklets/cbi/page_6.png",
      "assets/uam_booklets/cbi/page_7.png",
      "assets/uam_booklets/cbi/page_8.png",
      "assets/uam_booklets/cbi/page_9.png",
      "assets/uam_booklets/cbi/page_10.png",
      "assets/uam_booklets/cbi/page_11.png",
      "assets/uam_booklets/cbi/page_12.png",
      "assets/uam_booklets/cbi/page_13.png",
      "assets/uam_booklets/cbi/page_14.png",
      "assets/uam_booklets/cbi/page_15.png",
      "assets/uam_booklets/cbi/page_16.png",
      "assets/uam_booklets/cbi/page_17.png",
      "assets/uam_booklets/cbi/page_18.png",
      "assets/uam_booklets/cbi/page_19.png",
      "assets/uam_booklets/cbi/page_20.png",
      "assets/uam_booklets/cbi/page_21.png",
      "assets/uam_booklets/cbi/page_22.png",
      "assets/uam_booklets/cbi/page_23.png",
      "assets/uam_booklets/cbi/page_24.png",
      "assets/uam_booklets/cbi/page_25.png",
      "assets/uam_booklets/cbi/page_26.png",
      "assets/uam_booklets/cbi/page_27.png",
      "assets/uam_booklets/cbi/page_28.png",
      "assets/uam_booklets/cbi/page_29.png",
      "assets/uam_booklets/cbi/page_30.png",
      "assets/uam_booklets/cbi/page_31.png",
      "assets/uam_booklets/cbi/page_32.png",
      "assets/uam_booklets/cbi/page_33.png",
      "assets/uam_booklets/cbi/page_34.png",
      "assets/uam_booklets/cbi/page_35.png",
      "assets/uam_booklets/cbi/page_36.png",
      "assets/uam_booklets/cbi/page_37.png",
      "assets/uam_booklets/cbi/page_38.png",
      "assets/uam_booklets/cbi/page_39.png",
      "assets/uam_booklets/cbi/page_40.png",
      "assets/uam_booklets/cbi/page_41.png",
      "assets/uam_booklets/cbi/page_42.png",
      "assets/uam_booklets/cbi/page_43.png",
      "assets/uam_booklets/cbi/page_44.png",
      "assets/uam_booklets/cbi/page_45.png",
      "assets/uam_booklets/cbi/page_46.png",
      "assets/uam_booklets/cbi/page_47.png",
      "assets/uam_booklets/cbi/page_48.png",
      "assets/uam_booklets/cbi/page_49.png",
      "assets/uam_booklets/cbi/page_50.png",
      "assets/uam_booklets/cbi/page_51.png",
      "assets/uam_booklets/cbi/page_52.png",
      "assets/uam_booklets/cbi/page_53.png",
      "assets/uam_booklets/cbi/page_54.png",
      "assets/uam_booklets/cbi/page_55.png",
      "assets/uam_booklets/cbi/page_56.png",
      "assets/uam_booklets/cbi/page_57.png",
      "assets/uam_booklets/cbi/page_58.png",
      "assets/uam_booklets/cbi/page_59.png",
      "assets/uam_booklets/cbi/page_60.png",
      "assets/uam_booklets/cbi/page_61.png",
      "assets/uam_booklets/cbi/page_62.png",
      "assets/uam_booklets/cbi/page_63.png",
      "assets/uam_booklets/cbi/page_64.png",
      "assets/uam_booklets/cbi/page_65.png",
      "assets/uam_booklets/cbi/page_66.png",
      "assets/uam_booklets/cbi/page_67.png",
      "assets/uam_booklets/cbi/page_68.png",
      "assets/uam_booklets/cbi/page_69.png",
      "assets/uam_booklets/cbi/page_70.png",
      "assets/uam_booklets/cbi/page_71.png",
      "assets/uam_booklets/cbi/page_72.png",
      "assets/uam_booklets/cbi/page_73.png",
      "assets/uam_booklets/cbi/page_74.png",
      "assets/uam_booklets/cbi/page_75.png",
      "assets/uam_booklets/cbi/page_76.png",
      "assets/uam_booklets/cbi/page_77.png",
      "assets/uam_booklets/cbi/page_78.png",
      "assets/uam_booklets/cbi/page_79.png",
      "assets/uam_booklets/cbi/page_80.png",
      "assets/uam_booklets/cbi/page_81.png",
      "assets/uam_booklets/cbi/page_82.png",
      "assets/uam_booklets/cbi/page_83.png",
      "assets/uam_booklets/cbi/page_84.png",
      "assets/uam_booklets/cbi/page_85.png",
      "assets/uam_booklets/cbi/page_86.png",
      "assets/uam_booklets/cbi/page_87.png",
      "assets/uam_booklets/cbi/page_88.png",
      "assets/uam_booklets/cbi/page_89.png",
      "assets/uam_booklets/cbi/page_90.png",
      "assets/uam_booklets/cbi/page_91.png",
      "assets/uam_booklets/cbi/page_92.png",
      "assets/uam_booklets/cbi/page_93.png",
      "assets/uam_booklets/cbi/page_94.png",
      "assets/uam_booklets/cbi/page_95.png",
      "assets/uam_booklets/cbi/page_96.png",
      "assets/uam_booklets/cbi/page_97.png",
      "assets/uam_booklets/cbi/page_98.png",
      "assets/uam_booklets/cbi/page_99.png",
      "assets/uam_booklets/cbi/page_100.png",
      "assets/uam_booklets/cbi/page_101.png",
      "assets/uam_booklets/cbi/page_102.png",
      "assets/uam_booklets/cbi/page_103.png",
      "assets/uam_booklets/cbi/page_104.png",
      "assets/uam_booklets/cbi/page_105.png",
      "assets/uam_booklets/cbi/page_106.png",
      "assets/uam_booklets/cbi/page_107.png",
      "assets/uam_booklets/cbi/page_108.png",
      "assets/uam_booklets/cbi/page_109.png",
      "assets/uam_booklets/cbi/page_110.png",
      "assets/uam_booklets/cbi/page_111.png",
      "assets/uam_booklets/cbi/page_112.png",
      "assets/uam_booklets/cbi/page_113.png",
      "assets/uam_booklets/cbi/page_114.png",
      "assets/uam_booklets/cbi/page_115.png",
      "assets/uam_booklets/cbi/page_116.png",
      "assets/uam_booklets/cbi/page_117.png",
      "assets/uam_booklets/cbi/page_118.png",
      "assets/uam_booklets/cbi/page_119.png"
    ],
    "answers": {
      "1": "C",
      "2": "C",
      "7": "A",
      "9": "D",
      "14": "D",
      "15": "B",
      "10": "D",
      "11": "B",
      "12": "D",
      "13": "B",
      "16": "B",
      "17": "A",
      "18": "B",
      "19": "D",
      "20": "A",
      "21": "A",
      "22": "D",
      "23": "D",
      "24": "B",
      "25": "A",
      "26": "A",
      "27": "B",
      "28": "B",
      "29": "D",
      "30": "B",
      "31": "A",
      "32": "B",
      "33": "B",
      "34": "D",
      "35": "C",
      "36": "C",
      "37": "B",
      "38": "B",
      "39": "C",
      "40": "D",
      "41": "C",
      "42": "A",
      "43": "C",
      "44": "D",
      "45": "B",
      "46": "A",
      "47": "D",
      "48": "B",
      "49": "C",
      "50": "B",
      "51": "B",
      "52": "C",
      "53": "D",
      "54": "B",
      "55": "C",
      "56": "A",
      "57": "D",
      "59": "A",
      "60": "B",
      "61": "D",
      "62": "C",
      "63": "C",
      "64": "C",
      "65": "A",
      "66": "A",
      "67": "A",
      "68": "B",
      "69": "B",
      "70": "C",
      "72": "C",
      "73": "C",
      "74": "B",
      "76": "C",
      "78": "C",
      "79": "D",
      "80": "B",
      "82": "B",
      "83": "D",
      "84": "D",
      "85": "D",
      "86": "D",
      "87": "A",
      "88": "B",
      "89": "B",
      "90": "C",
      "92": "D",
      "93": "B",
      "94": "C",
      "95": "A",
      "96": "A",
      "97": "A",
      "98": "B",
      "99": "C",
      "100": "B",
      "3": "A",
      "4": "D",
      "5": "C",
      "6": "B",
      "8": "B",
      "58": "B",
      "71": "C",
      "75": "B",
      "77": "A",
      "81": "C",
      "91": "A"
    }
  },
  "cbs": {
    "pages": [
      "assets/uam_booklets/cbs/page_1.png",
      "assets/uam_booklets/cbs/page_2.png",
      "assets/uam_booklets/cbs/page_3.png",
      "assets/uam_booklets/cbs/page_4.png",
      "assets/uam_booklets/cbs/page_5.png",
      "assets/uam_booklets/cbs/page_6.png",
      "assets/uam_booklets/cbs/page_7.png",
      "assets/uam_booklets/cbs/page_8.png",
      "assets/uam_booklets/cbs/page_9.png",
      "assets/uam_booklets/cbs/page_10.png",
      "assets/uam_booklets/cbs/page_11.png",
      "assets/uam_booklets/cbs/page_12.png",
      "assets/uam_booklets/cbs/page_13.png",
      "assets/uam_booklets/cbs/page_14.png",
      "assets/uam_booklets/cbs/page_15.png",
      "assets/uam_booklets/cbs/page_16.png",
      "assets/uam_booklets/cbs/page_17.png",
      "assets/uam_booklets/cbs/page_18.png",
      "assets/uam_booklets/cbs/page_19.png",
      "assets/uam_booklets/cbs/page_20.png",
      "assets/uam_booklets/cbs/page_21.png",
      "assets/uam_booklets/cbs/page_22.png",
      "assets/uam_booklets/cbs/page_23.png",
      "assets/uam_booklets/cbs/page_24.png",
      "assets/uam_booklets/cbs/page_25.png",
      "assets/uam_booklets/cbs/page_26.png",
      "assets/uam_booklets/cbs/page_27.png",
      "assets/uam_booklets/cbs/page_28.png",
      "assets/uam_booklets/cbs/page_29.png",
      "assets/uam_booklets/cbs/page_30.png",
      "assets/uam_booklets/cbs/page_31.png",
      "assets/uam_booklets/cbs/page_32.png",
      "assets/uam_booklets/cbs/page_33.png",
      "assets/uam_booklets/cbs/page_34.png",
      "assets/uam_booklets/cbs/page_35.png",
      "assets/uam_booklets/cbs/page_36.png",
      "assets/uam_booklets/cbs/page_37.png",
      "assets/uam_booklets/cbs/page_38.png",
      "assets/uam_booklets/cbs/page_39.png",
      "assets/uam_booklets/cbs/page_40.png",
      "assets/uam_booklets/cbs/page_41.png",
      "assets/uam_booklets/cbs/page_42.png",
      "assets/uam_booklets/cbs/page_43.png",
      "assets/uam_booklets/cbs/page_44.png",
      "assets/uam_booklets/cbs/page_45.png",
      "assets/uam_booklets/cbs/page_46.png",
      "assets/uam_booklets/cbs/page_47.png",
      "assets/uam_booklets/cbs/page_48.png",
      "assets/uam_booklets/cbs/page_49.png",
      "assets/uam_booklets/cbs/page_50.png",
      "assets/uam_booklets/cbs/page_51.png",
      "assets/uam_booklets/cbs/page_52.png",
      "assets/uam_booklets/cbs/page_53.png",
      "assets/uam_booklets/cbs/page_54.png",
      "assets/uam_booklets/cbs/page_55.png",
      "assets/uam_booklets/cbs/page_56.png",
      "assets/uam_booklets/cbs/page_57.png",
      "assets/uam_booklets/cbs/page_58.png"
    ],
    "answers": {
      "41": "C",
      "42": "A",
      "43": "C",
      "44": "D",
      "45": "B",
      "46": "A",
      "47": "D",
      "48": "B",
      "49": "C",
      "50": "B",
      "51": "B",
      "52": "C",
      "53": "D",
      "54": "B",
      "55": "C",
      "56": "A",
      "57": "D",
      "58": "B",
      "59": "A",
      "60": "B",
      "61": "D",
      "62": "C",
      "63": "C",
      "64": "C",
      "65": "A",
      "66": "A",
      "67": "A",
      "68": "B",
      "69": "B",
      "70": "C",
      "71": "C",
      "72": "C",
      "73": "C",
      "74": "B",
      "75": "B",
      "76": "C",
      "77": "A",
      "78": "C",
      "80": "B",
      "79": "D",
      "81": "C",
      "82": "B",
      "83": "D",
      "86": "D",
      "87": "A",
      "88": "B",
      "89": "B",
      "90": "C",
      "91": "A",
      "92": "D",
      "93": "B",
      "95": "A",
      "96": "A",
      "97": "A",
      "98": "B",
      "99": "C",
      "100": "B",
      "103": "E",
      "104": "D",
      "105": "C",
      "106": "B",
      "107": "B",
      "108": "B",
      "110": "D",
      "1": "C",
      "2": "C",
      "7": "A",
      "9": "D",
      "14": "D",
      "15": "B",
      "10": "D",
      "11": "B",
      "12": "D",
      "13": "B",
      "16": "B",
      "17": "A",
      "18": "B",
      "19": "D",
      "20": "A",
      "21": "A",
      "22": "D",
      "23": "D",
      "24": "B",
      "25": "A",
      "26": "A",
      "27": "B",
      "28": "B",
      "29": "D",
      "30": "B",
      "31": "A",
      "32": "B",
      "33": "B",
      "34": "D",
      "35": "C",
      "36": "C",
      "37": "B",
      "38": "B",
      "39": "C",
      "40": "D",
      "84": "D",
      "85": "D",
      "94": "C",
      "3": "A",
      "4": "D",
      "5": "C",
      "6": "B",
      "8": "B",
      "101": "D",
      "102": "A",
      "109": "E"
    }
  },
  "chs": {
    "pages": [
      "assets/uam_booklets/chs/page_1.png",
      "assets/uam_booklets/chs/page_2.png",
      "assets/uam_booklets/chs/page_3.png",
      "assets/uam_booklets/chs/page_4.png",
      "assets/uam_booklets/chs/page_5.png",
      "assets/uam_booklets/chs/page_6.png",
      "assets/uam_booklets/chs/page_7.png",
      "assets/uam_booklets/chs/page_8.png",
      "assets/uam_booklets/chs/page_9.png",
      "assets/uam_booklets/chs/page_10.png",
      "assets/uam_booklets/chs/page_11.png",
      "assets/uam_booklets/chs/page_12.png",
      "assets/uam_booklets/chs/page_13.png",
      "assets/uam_booklets/chs/page_14.png",
      "assets/uam_booklets/chs/page_15.png",
      "assets/uam_booklets/chs/page_16.png",
      "assets/uam_booklets/chs/page_17.png",
      "assets/uam_booklets/chs/page_18.png",
      "assets/uam_booklets/chs/page_19.png",
      "assets/uam_booklets/chs/page_20.png",
      "assets/uam_booklets/chs/page_21.png",
      "assets/uam_booklets/chs/page_22.png",
      "assets/uam_booklets/chs/page_23.png",
      "assets/uam_booklets/chs/page_24.png",
      "assets/uam_booklets/chs/page_25.png",
      "assets/uam_booklets/chs/page_26.png",
      "assets/uam_booklets/chs/page_27.png",
      "assets/uam_booklets/chs/page_28.png",
      "assets/uam_booklets/chs/page_29.png",
      "assets/uam_booklets/chs/page_30.png",
      "assets/uam_booklets/chs/page_31.png",
      "assets/uam_booklets/chs/page_32.png",
      "assets/uam_booklets/chs/page_33.png",
      "assets/uam_booklets/chs/page_34.png",
      "assets/uam_booklets/chs/page_35.png",
      "assets/uam_booklets/chs/page_36.png",
      "assets/uam_booklets/chs/page_37.png",
      "assets/uam_booklets/chs/page_38.png",
      "assets/uam_booklets/chs/page_39.png",
      "assets/uam_booklets/chs/page_40.png",
      "assets/uam_booklets/chs/page_41.png",
      "assets/uam_booklets/chs/page_42.png",
      "assets/uam_booklets/chs/page_43.png",
      "assets/uam_booklets/chs/page_44.png",
      "assets/uam_booklets/chs/page_45.png",
      "assets/uam_booklets/chs/page_46.png",
      "assets/uam_booklets/chs/page_47.png",
      "assets/uam_booklets/chs/page_48.png",
      "assets/uam_booklets/chs/page_49.png",
      "assets/uam_booklets/chs/page_50.png",
      "assets/uam_booklets/chs/page_51.png",
      "assets/uam_booklets/chs/page_52.png",
      "assets/uam_booklets/chs/page_53.png",
      "assets/uam_booklets/chs/page_54.png",
      "assets/uam_booklets/chs/page_55.png",
      "assets/uam_booklets/chs/page_56.png",
      "assets/uam_booklets/chs/page_57.png",
      "assets/uam_booklets/chs/page_58.png"
    ],
    "answers": {
      "64": "C",
      "65": "A",
      "71": "C",
      "72": "C",
      "51": "B",
      "52": "C",
      "53": "D",
      "54": "B",
      "55": "C",
      "56": "A",
      "57": "D",
      "58": "B",
      "59": "A",
      "60": "B",
      "61": "D",
      "62": "C",
      "63": "C",
      "66": "A",
      "67": "A",
      "68": "B",
      "69": "B",
      "70": "C",
      "73": "C",
      "74": "B",
      "75": "B",
      "76": "C",
      "77": "A",
      "78": "C",
      "79": "D",
      "80": "B",
      "81": "C",
      "82": "B",
      "83": "D",
      "84": "D",
      "85": "D",
      "86": "D",
      "87": "A",
      "88": "B",
      "89": "B",
      "91": "A",
      "92": "D",
      "93": "B",
      "94": "C",
      "96": "A",
      "97": "A",
      "98": "B",
      "99": "C",
      "100": "B",
      "101": "E",
      "102": "C",
      "103": "B",
      "105": "D",
      "107": "D",
      "108": "D",
      "109": "A",
      "1": "C",
      "2": "C",
      "7": "A",
      "9": "D",
      "14": "D",
      "15": "B",
      "10": "D",
      "11": "B",
      "12": "D",
      "13": "B",
      "16": "B",
      "17": "A",
      "18": "B",
      "19": "D",
      "20": "A",
      "21": "A",
      "22": "D",
      "23": "D",
      "24": "B",
      "25": "A",
      "26": "A",
      "27": "B",
      "28": "B",
      "29": "D",
      "30": "B",
      "31": "A",
      "32": "B",
      "33": "B",
      "34": "D",
      "35": "C",
      "36": "C",
      "37": "B",
      "38": "B",
      "39": "C",
      "40": "D",
      "41": "C",
      "42": "A",
      "43": "C",
      "44": "D",
      "45": "B",
      "46": "A",
      "47": "D",
      "48": "B",
      "49": "C",
      "50": "B",
      "90": "C",
      "95": "A",
      "3": "A",
      "4": "D",
      "5": "C",
      "6": "B",
      "8": "B",
      "104": "D",
      "106": "A",
      "110": "C"
    }
  },
  "cyad": {
    "pages": [
      "assets/uam_booklets/cyad/page_1.png",
      "assets/uam_booklets/cyad/page_2.png",
      "assets/uam_booklets/cyad/page_3.png",
      "assets/uam_booklets/cyad/page_4.png",
      "assets/uam_booklets/cyad/page_5.png",
      "assets/uam_booklets/cyad/page_6.png",
      "assets/uam_booklets/cyad/page_7.png",
      "assets/uam_booklets/cyad/page_8.png",
      "assets/uam_booklets/cyad/page_9.png",
      "assets/uam_booklets/cyad/page_10.png",
      "assets/uam_booklets/cyad/page_11.png",
      "assets/uam_booklets/cyad/page_12.png",
      "assets/uam_booklets/cyad/page_13.png",
      "assets/uam_booklets/cyad/page_14.png",
      "assets/uam_booklets/cyad/page_15.png",
      "assets/uam_booklets/cyad/page_16.png",
      "assets/uam_booklets/cyad/page_17.png",
      "assets/uam_booklets/cyad/page_18.png",
      "assets/uam_booklets/cyad/page_19.png",
      "assets/uam_booklets/cyad/page_20.png",
      "assets/uam_booklets/cyad/page_21.png",
      "assets/uam_booklets/cyad/page_22.png",
      "assets/uam_booklets/cyad/page_23.png",
      "assets/uam_booklets/cyad/page_24.png",
      "assets/uam_booklets/cyad/page_25.png",
      "assets/uam_booklets/cyad/page_26.png",
      "assets/uam_booklets/cyad/page_27.png",
      "assets/uam_booklets/cyad/page_28.png",
      "assets/uam_booklets/cyad/page_29.png",
      "assets/uam_booklets/cyad/page_30.png",
      "assets/uam_booklets/cyad/page_31.png",
      "assets/uam_booklets/cyad/page_32.png",
      "assets/uam_booklets/cyad/page_33.png",
      "assets/uam_booklets/cyad/page_34.png",
      "assets/uam_booklets/cyad/page_35.png",
      "assets/uam_booklets/cyad/page_36.png",
      "assets/uam_booklets/cyad/page_37.png",
      "assets/uam_booklets/cyad/page_38.png",
      "assets/uam_booklets/cyad/page_39.png",
      "assets/uam_booklets/cyad/page_40.png",
      "assets/uam_booklets/cyad/page_41.png",
      "assets/uam_booklets/cyad/page_42.png",
      "assets/uam_booklets/cyad/page_43.png",
      "assets/uam_booklets/cyad/page_44.png",
      "assets/uam_booklets/cyad/page_45.png",
      "assets/uam_booklets/cyad/page_46.png",
      "assets/uam_booklets/cyad/page_47.png",
      "assets/uam_booklets/cyad/page_48.png",
      "assets/uam_booklets/cyad/page_49.png",
      "assets/uam_booklets/cyad/page_50.png",
      "assets/uam_booklets/cyad/page_51.png",
      "assets/uam_booklets/cyad/page_52.png",
      "assets/uam_booklets/cyad/page_53.png",
      "assets/uam_booklets/cyad/page_54.png",
      "assets/uam_booklets/cyad/page_55.png",
      "assets/uam_booklets/cyad/page_56.png",
      "assets/uam_booklets/cyad/page_57.png",
      "assets/uam_booklets/cyad/page_58.png",
      "assets/uam_booklets/cyad/page_59.png",
      "assets/uam_booklets/cyad/page_60.png",
      "assets/uam_booklets/cyad/page_61.png",
      "assets/uam_booklets/cyad/page_62.png"
    ],
    "answers": {
      "52": "C",
      "53": "D",
      "56": "A",
      "58": "B",
      "59": "A",
      "62": "C",
      "65": "A",
      "66": "A",
      "67": "A",
      "68": "B",
      "69": "B",
      "70": "C",
      "71": "C",
      "72": "C",
      "73": "C",
      "74": "B",
      "75": "B",
      "76": "C",
      "77": "A",
      "78": "C",
      "79": "D",
      "80": "B",
      "81": "C",
      "82": "B",
      "83": "D",
      "84": "D",
      "85": "D",
      "86": "D",
      "87": "A",
      "88": "B",
      "89": "B",
      "90": "C",
      "91": "A",
      "92": "D",
      "93": "B",
      "94": "C",
      "96": "A",
      "97": "A",
      "98": "B",
      "99": "C",
      "100": "B",
      "102": "E",
      "103": "B",
      "104": "C",
      "107": "D",
      "108": "C",
      "109": "E",
      "1": "C",
      "2": "C",
      "7": "A",
      "9": "D",
      "14": "D",
      "15": "B",
      "10": "D",
      "11": "B",
      "12": "D",
      "13": "B",
      "16": "B",
      "17": "A",
      "18": "B",
      "19": "D",
      "20": "A",
      "21": "A",
      "22": "D",
      "23": "D",
      "24": "B",
      "25": "A",
      "26": "A",
      "27": "B",
      "28": "B",
      "29": "D",
      "30": "B",
      "31": "A",
      "32": "B",
      "33": "B",
      "34": "D",
      "35": "C",
      "36": "C",
      "37": "B",
      "38": "B",
      "39": "C",
      "40": "D",
      "41": "C",
      "42": "A",
      "43": "C",
      "44": "D",
      "45": "B",
      "46": "A",
      "47": "D",
      "48": "B",
      "49": "C",
      "50": "B",
      "51": "B",
      "54": "B",
      "55": "C",
      "57": "D",
      "60": "B",
      "61": "D",
      "63": "C",
      "64": "C",
      "95": "A",
      "3": "A",
      "4": "D",
      "5": "C",
      "6": "B",
      "8": "B",
      "101": "D",
      "105": "C",
      "106": "A",
      "110": "B"
    }
  }
};
